### ISSUE TITLE
I have opened picgo. Why do I still report an error?

### ISSUE THREAD

**Issue by YangWaldon** [jjaychen1e/logseq-plugin-image-uploader#8]
the picgo is running······
![image](https://user-images.githubusercontent.com/49675185/169475874-5f660225-4cb4-4ae8-bef4-8de772cccf55.png)

**Comment by jjaychen1e** [comment]
> the picgo is running······
> ![image](https://user-images.githubusercontent.com/49675185/169475874-5f660225-4cb4-4ae8-bef4-8de772cccf55.png)

Did you install the plug-in from plug-in store? Currently only manually installed version can work.

**Comment by yanfulin** [comment]
I downloaded from Github and installed manually. I got the same CORS restriction message.

**Comment by jjaychen1e** [comment]
> I downloaded from Github and installed manually. I got the same CORS restriction message.

Please check the PicGo-Server setting:

<img width="912" alt="Screen Shot 2022-07-10 at 23 52 05" src="https://user-images.githubusercontent.com/31304335/178152120-a9f1b4e6-fa72-44e7-bd57-dd258c834da6.png">

Make sure it's enabled and listening to port 36677.

**Comment by yueyehechuwuyueming** [comment]
Well,I'm sure my picgo is enabled,but I got the same problem same as the above.
![image](https://user-images.githubusercontent.com/62372246/180245804-941df369-2e90-4be6-922f-23e748e5f947.png)
![image](https://user-images.githubusercontent.com/62372246/180246006-12dcb5e7-c0b2-4191-9b9d-3a15a1672b65.png)

**Comment by jjaychen1e** [comment]
@YangWaldon @yanfulin @yueyehechuwuyueming Please try [v0.0.10](https://github.com/JJAYCHEN1e/logseq-plugin-image-uploader/releases/tag/v0.0.10), I add the detailed response content from PicGo to logseq's developer tool for each upload, could you check it out and give me the response content?

Here is how you can toggle logseq's developer  tool:

<img width="272" alt="image" src="https://user-images.githubusercontent.com/31304335/180629555-9f2547ee-b6e0-405c-93c0-682b7302925e.png">

**Comment by yueyehechuwuyueming** [comment]
I've tried v0.09,is this "response content" that you said?







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JJAYCHEN1e/logseq-plugin-image-uploader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月24日(星期天) 上午10:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JJAYCHEN1e/logseq-plugin-image-uploader] I have opened picgo. Why do I still report an error? (Issue #8)





 
@YangWaldon @yanfulin @yueyehechuwuyueming Please try v0.0.9, I add the detailed response content from PicGo to logseq's developer tool for each upload, could you check it out and give me the response content?
 
Here is how you can toggle logseq's developer  tool:

**Comment by jjaychen1e** [comment]
@yueyehechuwuyueming Open the developer tool, and try to upload an image, you will see a log message here:

<img width="875" alt="image" src="https://user-images.githubusercontent.com/31304335/180633165-3a53c8ba-0ad0-4ba2-addb-8d3fad895fb4.png">

I release [v0.0.10](https://github.com/JJAYCHEN1e/logseq-plugin-image-uploader/releases/tag/v0.0.10) which fix a bug causes upload failure. Could you provide a screenshot of the developer tool's console when upload failed?

**Comment by yueyehechuwuyueming** [comment]
I've update by v0.0.10 and I only opened this plugin.Is this screenshot?






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JJAYCHEN1e/logseq-plugin-image-uploader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月24日(星期天) 中午1:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JJAYCHEN1e/logseq-plugin-image-uploader] I have opened picgo. Why do I still report an error? (Issue #8)





 
@yueyehechuwuyueming Open the developer tool, and try to upload an image, you will see a log message here:
 

 
I release v0.0.10 which fix a bug causes upload failure. Could you provide a screenshot of the developer tool's console when upload failed?

**Comment by jjaychen1e** [comment]
@yueyehechuwuyueming I can't see any images in your comment. You can upload images in the web version of GitHub instead of email: https://github.com/JJAYCHEN1e/logseq-plugin-image-uploader/issues/8

**Comment by yueyehechuwuyueming** [comment]
oh,I am sorry.I have not recognized it.
![image](https://user-images.githubusercontent.com/62372246/180634105-8b9d5ddf-ccdc-495d-bc5a-fc263f68094f.png)

**Comment by jjaychen1e** [comment]
> oh,I am sorry.I have not recognized it.
> ![image](https://user-images.githubusercontent.com/62372246/180634105-8b9d5ddf-ccdc-495d-bc5a-fc263f68094f.png)

It says the upload is blocked due to CORS policy. Do you install it from the GitHub release page or Logseq's Plugin Store? I haven't tested this plugin in Windows, but it works well in macOS if it's installed manually from the GitHub release page. I think they should behave same in both platforms.

**Comment by hyjwonder** [comment]
I have the same issue:
1. MacOS Monterey (12.5);
2. Logseq 0.8.0, turned on Dev mode;
3. PigGo server is running at desired port;
4. Installed the plugin from Github;
5. I can see that the image is uploaded via PigGo successfully.
6. Error msg in Logseq: 
<img width="392" alt="CleanShot 2022-08-10 at 13 33 40@2x" src="https://user-images.githubusercontent.com/77609410/183823411-bd6d21c8-5ba6-413a-b275-6a9ebafc2444.png">
<img width="535" alt="CleanShot 2022-08-10 at 13 34 37@2x" src="https://user-images.githubusercontent.com/77609410/183823564-0ec7c2ed-e701-45a0-9f97-41bb132d4003.png">

<img width="555" alt="CleanShot 2022-08-10 at 13 38 31@2x" src="https://user-images.githubusercontent.com/77609410/183823882-fa79d7bf-2dd0-4cfe-a414-74429e4ca12c.png">

**Comment by jjaychen1e** [comment]
@YangWaldon @yanfulin @yueyehechuwuyueming @hyjwonder Now Logseq provides an option to run the plugin out of the sandbox if permitted, and I've successfully requested the permission, you can try installing the plugin directly from the marketplace, it should resolve the CORS issue. Any feedback is welcome.

**Comment by hyjwonder** [comment]
Thanks @JJAYCHEN1e . I followed your advice and installed it from within logseq. But still not successful when trying to upload an image (Though I can see from PicGo that the image has been uploaded succesfully). The error msg:
![CleanShot 2022-08-11 at 14 02 16@2x](https://user-images.githubusercontent.com/77609410/184073108-b4655cc0-502a-47ff-bd83-40d662683f86.png)
<img width="561" alt="CleanShot 2022-08-11 at 14 04 49@2x" src="https://user-images.githubusercontent.com/77609410/184073309-667d5e1c-dc33-4c48-a8b7-cb610f4d9b3d.png">

My PicGo server config:
<img width="774" alt="CleanShot 2022-08-11 at 14 09 25@2x" src="https://user-images.githubusercontent.com/77609410/184073796-8c0fc30e-adb7-4c76-b083-02e647758be0.png">

**Comment by jjaychen1e** [comment]
@hyjwonder According to your log, the request origin is still `lsp://logseq.io`, which is not supposed to happen. The plugin downloaded from the marketplace now should use the file protocol instead of the lsp protocol. I don't know if it's a latency or  local cache issue, because I changed the setting in the [marketplace center](https://github.com/logseq/marketplace/pull/233) which is based on a Github repo. Please try to uninstall the plugin and install it again, or reinstall the Logseq. For myself, it works right after I change the setting.

**Comment by hyjwonder** [comment]
> @hyjwonder According to your log, the request origin is still `lsp://logseq.io`, which is not supposed to happen. The plugin downloaded from the marketplace now should use the file protocol instead of the lsp protocol. I don't know if it's a latency or local cache issue, because I changed the setting in the [marketplace center](https://github.com/logseq/marketplace/pull/233) which is based on a Github repo. Please try to uninstall the plugin and install it again, or reinstall the Logseq. For myself, it works right after I change the setting.

Hi, I reinstalled the plugin. Now it works fine. Thanks for your help!
